### ISSUE TITLE
[CoderSchool Android] Project 1 - Instagram - Ready for review

### ISSUE THREAD

**Issue by yasuosm** [yasuosm/coderschool-project1-instagram-client#1]
My app is complete, please review. /cc @coderschoolreview

**Comment by hoanle** [comment]
@yasuosm 

## Week 1: Instagram Viewer

:+1: thank you for your submission. The goal of this homework was to teach you `RelativeLayout`, `ListView`, networking with APIs, and loading remote images. These concepts are the foundation of nearly every app. 

A few notes after checking out the code:
- Although the prj is small-scope, you should setup different package for each module
- Good layout, proper view naming, usage of sp/dp, margin and relative placement rules
- Glad you thought about error handling for invalid or empty input cases
- Good to see you playing around with RelativeLayout. RelativeLayout is one of the most powerful responsive-first layout systems
- Consider overriding onFailure method in JsonHttpResponseHandler to handle network failures appropriately.
- Good job using the ViewHolder pattern to improve performance of photos ListView
- Nice to see you used the SwipeRefreshLayout for easy stream refreshes
- Good to see that you were able to successfully read the json object to display comments for photos. 
- Good job using the ButterKnife library annotations for declaring handles to view objects.
- Using Gson can spare a lot of time parsing json

You can read a detailed [Project 1 Feedback Guide here](http://learning.coderschool.vn/snippets/intro_to_android/project_1_feedback) which covers the most common points we see for this project, if you'd like to evaluate yourself further.

**Comment by yasuosm** [comment]
@hoanle 
Thank you for your review. I will read the Feedback Guide :+1:
